### ISSUE TITLE
Remove references to sun packages

### ISSUE THREAD

**Issue by ptrcnull** [SarutaSan72/Yass#94]
Using `com.sun.*` packages is considered bad practice -  usage of `com.sun.xml.internal.ws.api` in `I18.java` breaks compilation under javac 1.8.0_302
```
src/yass/I18.java:21: error: package com.sun.xml.internal.ws.api does not exist
import com.sun.xml.internal.ws.api.ResourceLoader;
                                  ^
```
