### PR TITLE
Remove unused reference to com.sun package

### LINKED ISSUE #94: Remove references to sun packages
Using `com.sun.*` packages is considered bad practice -  usage of `com.sun.xml.internal.ws.api` in `I18.java` breaks compilation under javac 1.8.0_302
```
src/yass/I18.java:21: error: package com.sun.xml.internal.ws.api does not exist
import com.sun.xml.internal.ws.api.ResourceLoader;
                                  ^
```

### PR DESCRIPTION
**Pull request by ptrcnull**
Closes #94

### CODE REVIEW

**Comment by ptrcnull** [comment]
hi could this please be merged soon
